import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-12 bg-stone-800">
        <h1 className="text-4xl font-bold font-title text-white">
          Hello World
        </h1>
        <p className="text-white">I would like to be great</p>
      </div>
    </>
  )
}
